### ISSUE TITLE
how to add tis module in angular 2

### ISSUE THREAD

**Issue by ajayadglobal360-AGL** [ArunMichaelDsouza/ng-image-appear#6]
This is great module of image placeholder. but i want to add this in angular 2 project so please guide me how to add this in angular 2 project.

**Comment by ArunMichaelDsouza** [comment]
Hi, apologies for the late reply. Please take a look at the official guide - https://angular.io/guide/upgrade, you will be able to find migration details there. I really don't have time to work on an Angular 2 compatible version for this module. Maybe you can send in a pull request for that ? Please feel free!
