### ISSUE TITLE
Fix for IOS / Safari / Mac / Firefox

### ISSUE THREAD

**Issue by jommega** [ArunMichaelDsouza/ng-image-appear#8]
REPLACE

>                    if(element[0].complete) {
>                         loadImage();
>                     }

WITH

>                     if(element[0].complete && element[0].naturalWidth > 0) {
>                         loadImage();
>                     }

This work and correct the issue in ios, safari, firefox and ie....

**Comment by ArunMichaelDsouza** [comment]
Hi @jommega! Thank you for pointing out the issue. Would get this fixed!

**Comment by ArunMichaelDsouza** [comment]
Fixed in [v1.11.6](https://github.com/ArunMichaelDsouza/ng-image-appear/releases/tag/v1.11.6)
